// api/report.js — serves pre-generated report from GitHub
// Data is generated by Python script and uploaded to public/report_data.json

module.exports = async (req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.status(200).end();

  // Just redirect to the static JSON file served by Vercel
  return res.redirect(302, "/report_data.json");
};
